-- BIST Mini Project 1기 초기 세팅 SQL (Oracle)

-- 1. 샘플 테이블 삭제 (기존 테이블 존재 시)
-- DROP TABLE SAMPLE;
-- DROP SEQUENCE SEQ_SAMPLE_ID;

-- 2. 샘플 테이블 생성
CREATE TABLE SAMPLE (
    SAMPLE_ID NUMBER PRIMARY KEY,
    TESTSTR   VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE SAMPLE IS '샘플 테이블';
COMMENT ON COLUMN SAMPLE.SAMPLE_ID IS '샘플 고유 ID';
COMMENT ON COLUMN SAMPLE.TESTSTR IS '테스트 문자열';

-- 3. 샘플 ID 시퀀스 생성
CREATE SEQUENCE SEQ_SAMPLE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 4. 초기 데이터 삽입 (선택 사항)
INSERT INTO SAMPLE (SAMPLE_ID, TESTSTR) VALUES (SEQ_SAMPLE_ID.NEXTVAL, '초기 데이터 1');

COMMIT;
